---
title: "Conferences"
date: 2017-09-12T23:06:54+08:00
---

Here are some conferences that I've attended recently and would recommend for math students.
I learned a lot from the conferences talks and made some really good friends. A big thank you to all the conference organizers! 

### For Women

* [Women in Data Science](http://www.widsconference.org/): A series of events held at 20+ locations worldwide.
* [IAS Women and Mathematics Program](http://www.math.ias.edu/wam): A 2-week conference for women in math at all levels. A great mix of talks, mini courses, and volunteering activities.
* [Graduate Research Opportunities for Women (GROW)](http://www.math.northwestern.edu/events/conferences/graduate-research-opportunities-for-women.html): A 2-day conference for undergraduate women interested in graduate math research. 

### General

* [Mathematical Foundations of Computer Science](http://mfcs2017.cs.aau.dk): A European conference focused on theoretical computer science.
* [Probability and Statistics in Forensic Science](https://www.newton.ac.uk/event/fos): This is a one-time program, but there are many other workshops and programs at Issac Newton Institute.
* [Pacific Coast Undergraduate Math Conference](http://www.pcumc-math.org/): A friendly undergrad math conference, nice experience as a first conference.
